version: '3.5'

volumes:
  trustanchors:

services:

  trust:
    image: indigoiam/trustanchors
    environment:
      - FORCE_TRUST_ANCHORS_UPDATE=1
    volumes:
      - trustanchors:/etc/grid-security/certificates

  storm-testsuite:
    image: italiangrid/storm-testsuite:nightly
    container_name: ${STORM_TESTSUITE_CONTAINER_NAME}
    #entrypoint: sleep infinity
    entrypoint: sh /assets/run_testsuite.sh
    environment:
      - TESTSUITE_BRANCH
      - TESTSUITE_EXCLUDE
      - TESTSUITE_SUITE
      - STORM_STORAGE_ROOT_DIR
      - CDMI_CLIENT_SECRET
      - IAM_USER_PASSWORD
      - DAV_HOST
      - GFTP_HOST
      - STORM_BE_HOST
      - STORM_FE_HOST
      - CDMI_ENDPOINT
      - VOMS_FAKE
      - OUTPUT_DIRECTORY
      - STORM_XMLRPC_TOKEN
    depends_on:
      - trust
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - ./assets:/assets
