version: '3.5'

volumes:
  trustanchors:

services:

  trust:
    image: indigoiam/egi-trustanchors:igi-test-ca
    environment:
      - FORCE_TRUST_ANCHORS_UPDATE=1
    volumes:
      - trustanchors:/etc/grid-security/certificates

  storm-testsuite:
    image: italiangrid/storm-testsuite:latest
    container_name: ${STORM_TESTSUITE_CONTAINER_NAME}
    #entrypoint: sleep infinity
    entrypoint: sh /assets/run_testsuite.sh
    environment:
      - TESTSUITE_BRANCH
      - TESTSUITE_EXCLUDE
      - TESTSUITE_SUITE
      - STORM_STORAGE_ROOT_DIR
      - STORM_GRIDFTP_HOSTNAME
      - STORM_BACKEND_HOSTNAME
      - STORM_WEBDAV_HOSTNAME
      - STORM_FRONTEND_HOSTNAME
      - OUTPUT_DIRECTORY
    depends_on:
      - trust
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - ./assets:/assets
